apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: liquibase-update
spec:
  workspaces:
    - name: output
  steps:
    - name: run-liquibase
      image: liquibase/liquibase:latest
      script: |
        #!/bin/sh
        ls -R $(workspaces.output.path)/src/main/resources
        echo "pwd: "
        pwd
        
        echo "copy"
        echo "------------------------------"
        cp /workspace/output/src/main/resources/liquibase/changelog.xml /liquibase/changelog.xml
        echo "------------------------------"
        echo "check"
        ls /liquibase
        echo "------------------------------"
        echo "HELP"
        liquibase update --help
        echo "------------------------------"
        liquibase --version
        echo "------------------------------"
        echo "Verifying changelog file:"
        if [ -f "$(workspaces.output.path)/src/main/resources/liquibase/changelog.xml" ]; then
          echo "Found changelog.xml at $(workspaces.output.path)/src/main/resources/liquibase/changelog.xml"
        else
          echo "changelog.xml not found!"
          exit 1
        fi

        echo "------------------------------"
        echo "copy 2"
        cp /workspace/output/src/main/resources/liquibase.properties /liquibase/liquibase.properties
        ls -la
        echo "------------------------------"

        liquibase \
        --defaults-file=/liquibase/liquibase.properties \
        --classpath=$(workspaces.output.path)/src/main/resources/mysql-connector-j-9.1.0.jar \
        --changelog-file=/liquibase/changelog.xml \ 
        update