apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: liquibase-update
spec:
  workspaces:
    - name: output
  steps:
    - name: overwrite-example-changelog
      image: alpine:latest
      script: |
        #!/bin/sh
        cp $(workspaces.output.path)/src/main/resources/liquibase/changelog.xml /liquibase/examples/xml/example-changelog.xml

    - name: run-liquibase
      image: liquibase/liquibase:latest
      script: |
        #!/bin/sh
        echo "### Verificando el changelog ###"
        liquibase \
          --defaultsFile=$(workspaces.output.path)/src/main/resources/liquibase.properties \
          --classpath=$(workspaces.output.path)/src/main/resources/mysql-connector-j-9.1.0.jar \
          update