apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-mysql-deployment
  labels:
    app: tekton-mysql-deployment
spec:
  selector:
    matchLabels:
      app: tekton-mysql-pod
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tekton-mysql-pod
      annotations:
        pod-name: tekton-mysql-pod
    spec:
      containers:
      - image: mysql:8.4
        name: tekton-mysql-pod
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ""  # empty password as per docker-compose
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
        - name: MYSQL_USER
          value: "petclinic"
        - name: MYSQL_PASSWORD
          value: "petclinic"
        - name: MYSQL_DATABASE
          value: "petclinic"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d  # Mount init scripts here
        #resources:
        #  requests:
        #    cpu: "100m"
        #    memory: "512Mi"
        #  limits:
        #    cpu: "1000m"
        #    memory: "1Gi"
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc-tekton
      - name: mysql-initdb
        emptyDir: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-tekton
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
