apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ci-pipeline-run
  annotations:
    tekton.dev/pod-template: |
      metadata:
        annotations:
          tekton.dev/garbage-collect-on-completion: "true" # Habilita la eliminación de pods
spec:      
  pipelineRef:
    name: ci-pipeline
      #  podTemplate:
      #securityContext:
      #fsGroup: 65532
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        metadata:
          name: build-workspace-pvc
          annotations:
            tekton.dev/volume-delete: "true"
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: docker-credentials
      secret:
        secretName: docker-credentials
  params:
    - name: repo-url
      value: https://github.com/ignasijuez/CICD_tekton.git
    - name: image-reference
      value: juezignasi/tekton-app:latest
    - name: SONAR_PROJECT_KEY
      value: ignasijuez_tekton
    - name: SONAR_ORGANIZATION
      value: ignasijuez
