apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"maven-repo-cache-pvc","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5Gi"}}}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
      volume.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
    finalizers:
    - kubernetes.io/pvc-protection
    name: maven-repo-cache-pvc
    namespace: default
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: standard
    volumeMode: Filesystem
    volumeName: pvc-0a1e45e4-693a-4412-8774-3f52cd47280c
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"mysql-pvc-ga","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}}}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
      volume.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
    finalizers:
    - kubernetes.io/pvc-protection
    name: mysql-pvc-ga
    namespace: default
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
    volumeMode: Filesystem
    volumeName: pvc-db92d056-aefd-45d3-be04-091b2543b883
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"mysql-pvc-jenkins","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}}}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
      volume.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
    finalizers:
    - kubernetes.io/pvc-protection
    name: mysql-pvc-jenkins
    namespace: default
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
    volumeMode: Filesystem
    volumeName: pvc-a1203622-6992-4e45-a7ec-5ce295c4a3dc
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"mysql-pvc-tekton","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}}}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
      volume.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
    finalizers:
    - kubernetes.io/pvc-protection
    name: mysql-pvc-tekton
    namespace: default
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
    volumeMode: Filesystem
    volumeName: pvc-5276b522-e201-49a8-9141-8129dcc92052
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
      volume.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-1fa1b7487a
    namespace: default
    ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: ci-pipeline-run-dvl55
      uid: 682bef98-d1b6-450b-991e-d70de0c1b2b5
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
    volumeMode: Filesystem
    volumeName: pvc-431802ed-c892-418d-ba40-8e85107d4cb3
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
      volume.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-29b2e89128
    namespace: default
    ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: ci-pipeline-run-74z8s
      uid: 5d815596-3889-492b-a23c-7c542c3f85ad
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
    volumeMode: Filesystem
    volumeName: pvc-7353bfd6-c914-44e8-8e66-27b8f8b26fcc
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
      volume.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-2b59fecc3e
    namespace: default
    ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: ci-pipeline-run-rj4mt
      uid: 4d169175-32b1-44df-b72a-2434d84ffe01
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
    volumeMode: Filesystem
    volumeName: pvc-eabe394c-73bf-45c8-95d3-a0e71462089c
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
      volume.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-30a51890ad
    namespace: default
    ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: ci-pipeline-run-d4pgb
      uid: e8f92031-e16a-49ea-87f8-0f3e69bdb2c5
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
    volumeMode: Filesystem
    volumeName: pvc-16e55e98-0b40-42bc-8bcc-a9f10ab64940
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
      volume.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-313a2d6dde
    namespace: default
    ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: ci-pipeline-run-wf6tj
      uid: 000e6eae-13cd-406b-b5bc-cb3e6ae5a30d
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
    volumeMode: Filesystem
    volumeName: pvc-0e156b48-da44-4b3f-b304-1a964af5edfa
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
      volume.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-44e35225a6
    namespace: default
    ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: ci-pipeline-run-dv57s
      uid: d4177692-766c-466f-aafa-b194fccf0311
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
    volumeMode: Filesystem
    volumeName: pvc-f04300ca-76bc-42e7-b8c4-9cf8207ad46a
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
      volume.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-49f61bfff7
    namespace: default
    ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: ci-pipeline-run-g8zsc
      uid: 05ce91c2-eae2-40be-893a-758fb25d79f2
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
    volumeMode: Filesystem
    volumeName: pvc-ed3afffe-8487-4132-ba8b-109325a6be7c
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
      volume.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-742a46c236
    namespace: default
    ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: ci-pipeline-run-tmzcv
      uid: 4847540a-5740-4543-a463-5ac2bcca8abe
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
    volumeMode: Filesystem
    volumeName: pvc-d86c9454-576c-45ab-9588-c4912e935c13
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
      volume.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-7df4c6dd1a
    namespace: default
    ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: ci-pipeline-run-cdhg2
      uid: 98400f45-4022-4ac0-8b79-321b840b7251
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
    volumeMode: Filesystem
    volumeName: pvc-3ff3f3e0-bed6-4c9d-acef-416d6159650f
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
      volume.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-85e0f692f1
    namespace: default
    ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: ci-pipeline-run-vfmjv
      uid: ce4a45e5-1c09-4bc0-9cb2-0487711ec00a
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
    volumeMode: Filesystem
    volumeName: pvc-cdc80b0a-f51f-4e49-932d-6496287dde27
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
      volume.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-fc493fcfe5
    namespace: default
    ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: ci-pipeline-run-jpbjr
      uid: 5a49202e-2cb8-4928-a4e7-67d503625a90
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
    volumeMode: Filesystem
    volumeName: pvc-d3ba97ea-2005-4466-b3fe-eec0ef40e6e8
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
      volume.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-fe0f7e77d3
    namespace: default
    ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: ci-pipeline-run-m7wlm
      uid: d9ec7bc0-20b2-480d-beb4-4feb3e641f65
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
    volumeMode: Filesystem
    volumeName: pvc-b7279076-57f2-4dbe-99a7-9bf30206be6e
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
      volume.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/instance: prometheus
      app.kubernetes.io/name: alertmanager
    name: storage-prometheus-alertmanager-0
    namespace: default
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: standard
    volumeMode: Filesystem
    volumeName: pvc-416547e6-4662-4b58-8997-41f4d901444d
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
