apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-all-tests
spec:
  description: |
    This task runs all tests (unit and integration) after the app is deployed.
  workspaces:
    - name: output
  steps:
    - name: run-tests
      image: maven:3.8.7-eclipse-temurin-17
      script: |
        #!/usr/bin/env sh
        cd $(workspaces.output.path)
        mvn test
