apiVersion: v1
items:
- apiVersion: v1
  imagePullSecrets:
  - name: dockerhub-secret
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:17Z"
    name: default
    namespace: default
    resourceVersion: "736558"
    uid: b5581c7e-257a-4d5c-8d8b-a92d22b9a040
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"tekton-robot","namespace":"default"}}
    creationTimestamp: "2024-10-01T08:07:18Z"
    name: tekton-robot
    namespace: default
    resourceVersion: "75863"
    uid: d8958701-91db-424d-ba25-2824303b3bc7
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"tekton-triggers-sa","namespace":"default"}}
    creationTimestamp: "2024-10-30T16:20:12Z"
    name: tekton-triggers-sa
    namespace: default
    resourceVersion: "2042066"
    uid: 16aa70af-c7c7-4421-a12a-c29b3a1d3b73
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:17Z"
    name: default
    namespace: kube-node-lease
    resourceVersion: "317"
    uid: da636fdd-0143-4241-b23e-cc99bc2cddd6
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:17Z"
    name: default
    namespace: kube-public
    resourceVersion: "318"
    uid: 8f20a66f-8397-4327-ab46-335462e91568
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:15Z"
    name: attachdetach-controller
    namespace: kube-system
    resourceVersion: "295"
    uid: ffb883cd-50fe-40bf-a01d-fcf61b3448c9
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:14Z"
    name: bootstrap-signer
    namespace: kube-system
    resourceVersion: "287"
    uid: 23eeb78d-e4e2-4a1c-9ee8-1c57f601af83
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:13Z"
    name: certificate-controller
    namespace: kube-system
    resourceVersion: "280"
    uid: a88a104e-60bb-443b-825f-ce2ce98333d0
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:13Z"
    name: clusterrole-aggregation-controller
    namespace: kube-system
    resourceVersion: "284"
    uid: 82ac975a-1056-46b8-a352-18c24a1c2696
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:11Z"
    name: coredns
    namespace: kube-system
    resourceVersion: "243"
    uid: 291fd723-55d7-46cd-a949-853fa883fb0d
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:11Z"
    name: cronjob-controller
    namespace: kube-system
    resourceVersion: "229"
    uid: c7c93e36-58d3-4444-ba96-52791edd7116
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:13Z"
    name: daemon-set-controller
    namespace: kube-system
    resourceVersion: "272"
    uid: 847e954d-421b-4510-97bd-bf294124a609
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:17Z"
    name: default
    namespace: kube-system
    resourceVersion: "319"
    uid: aad1cf1b-2266-4790-a1f8-46e1f78a1a44
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:11Z"
    name: deployment-controller
    namespace: kube-system
    resourceVersion: "227"
    uid: 4751015f-1088-4794-b38f-b431160495bd
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:13Z"
    name: disruption-controller
    namespace: kube-system
    resourceVersion: "279"
    uid: 809d9e18-2044-4164-b019-934218c64623
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:11Z"
    name: endpoint-controller
    namespace: kube-system
    resourceVersion: "234"
    uid: 6be0670e-a6bf-4542-852c-ce6d0c8fbd4b
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:12Z"
    name: endpointslice-controller
    namespace: kube-system
    resourceVersion: "267"
    uid: d5f2aab5-832a-4d0e-89bd-a322698e9a66
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:16Z"
    name: endpointslicemirroring-controller
    namespace: kube-system
    resourceVersion: "296"
    uid: dbeda90c-865a-4a73-a7db-94e805c43262
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:14Z"
    name: ephemeral-volume-controller
    namespace: kube-system
    resourceVersion: "290"
    uid: c2d08916-cad7-4a90-a548-60fd2218f46c
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:12Z"
    name: expand-controller
    namespace: kube-system
    resourceVersion: "252"
    uid: e33f7cfb-9fa5-4c94-a4cc-51da6eededa8
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:11Z"
    name: generic-garbage-collector
    namespace: kube-system
    resourceVersion: "235"
    uid: 69c4e3ac-d32b-46f8-9e19-2812c1b664af
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:11Z"
    name: horizontal-pod-autoscaler
    namespace: kube-system
    resourceVersion: "249"
    uid: e5717de3-be69-44fa-9fdc-201f5bd55918
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:11Z"
    name: job-controller
    namespace: kube-system
    resourceVersion: "231"
    uid: 03ee1957-5903-4443-8fc3-763f69a4791d
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:12Z"
    name: kube-proxy
    namespace: kube-system
    resourceVersion: "250"
    uid: 630c6a9f-e980-4ef1-8e7e-e16b8fdca644
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:11Z"
    name: legacy-service-account-token-cleaner
    namespace: kube-system
    resourceVersion: "232"
    uid: fa64c777-37b1-4943-a119-531553b96083
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"k8s-app":"metrics-server"},"name":"metrics-server","namespace":"kube-system"}}
    creationTimestamp: "2024-10-22T11:43:28Z"
    labels:
      k8s-app: metrics-server
    name: metrics-server
    namespace: kube-system
    resourceVersion: "1554843"
    uid: 61a0c71e-48db-4d99-a836-ea9dd49d6808
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:15Z"
    name: namespace-controller
    namespace: kube-system
    resourceVersion: "292"
    uid: 1a656b22-626a-4713-ba74-32776eb21b4d
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:14Z"
    name: node-controller
    namespace: kube-system
    resourceVersion: "289"
    uid: 3b8bb83c-dd91-4285-be3e-e0683be17175
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:15Z"
    name: persistent-volume-binder
    namespace: kube-system
    resourceVersion: "294"
    uid: 47cf299d-ccc4-4d14-80e8-561685f73ed3
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:12Z"
    name: pod-garbage-collector
    namespace: kube-system
    resourceVersion: "268"
    uid: 3f0f8eee-6c24-4b82-ac30-2a8b7f00cf29
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:13Z"
    name: pv-protection-controller
    namespace: kube-system
    resourceVersion: "285"
    uid: 77e5deca-4cf6-412e-b365-886cad8607c0
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:11Z"
    name: pvc-protection-controller
    namespace: kube-system
    resourceVersion: "230"
    uid: 19f6455e-c0a4-4a07-8d7e-7cf43a8ecc9b
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:11Z"
    name: replicaset-controller
    namespace: kube-system
    resourceVersion: "228"
    uid: 608b717c-08f6-45ae-b55f-3fbffeb6754e
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:16Z"
    name: replication-controller
    namespace: kube-system
    resourceVersion: "297"
    uid: fc683d0f-060d-4c9e-b765-e1bf17fdd673
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:15Z"
    name: resourcequota-controller
    namespace: kube-system
    resourceVersion: "291"
    uid: 82c9d306-0187-47a5-ac21-9da50ce9dafd
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:12Z"
    name: root-ca-cert-publisher
    namespace: kube-system
    resourceVersion: "261"
    uid: f3da4c5a-d49c-4800-bbd4-fe7242a0cbf6
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:14Z"
    name: service-account-controller
    namespace: kube-system
    resourceVersion: "286"
    uid: 8d825ab6-14f3-4f4b-b6b9-b648dae1dc2a
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:12Z"
    name: service-controller
    namespace: kube-system
    resourceVersion: "256"
    uid: 789e92ed-99dd-47cc-b172-ac48f54aad4c
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:15Z"
    name: statefulset-controller
    namespace: kube-system
    resourceVersion: "293"
    uid: ee41a0b2-72ef-4b5e-aaeb-99de417b8294
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile"},"name":"storage-provisioner","namespace":"kube-system"}}
    creationTimestamp: "2024-09-30T10:29:13Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
    name: storage-provisioner
    namespace: kube-system
    resourceVersion: "273"
    uid: 6519acb2-1aa8-40fe-8df3-8ee4fcd5abcf
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:14Z"
    name: token-cleaner
    namespace: kube-system
    resourceVersion: "288"
    uid: 7f0263e1-de14-45ec-97e5-ccf934e1cbcb
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:12Z"
    name: ttl-after-finished-controller
    namespace: kube-system
    resourceVersion: "254"
    uid: 1cc65bce-fd24-4d42-88e4-fd3e4e612159
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:13Z"
    name: ttl-controller
    namespace: kube-system
    resourceVersion: "281"
    uid: 64f32ee4-2e99-48b4-b911-998df9b616fe
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:11Z"
    name: validatingadmissionpolicy-status-controller
    namespace: kube-system
    resourceVersion: "233"
    uid: a5677349-4559-41dc-aa39-0adf94738bb2
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-09-30T10:29:25Z"
    name: default
    namespace: kubernetes-dashboard
    resourceVersion: "374"
    uid: 7c81ce17-2e41-4757-8e51-6263cb9d5e22
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","k8s-app":"kubernetes-dashboard","kubernetes.io/minikube-addons":"dashboard"},"name":"kubernetes-dashboard","namespace":"kubernetes-dashboard"}}
    creationTimestamp: "2024-09-30T10:29:25Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      k8s-app: kubernetes-dashboard
      kubernetes.io/minikube-addons: dashboard
    name: kubernetes-dashboard
    namespace: kubernetes-dashboard
    resourceVersion: "398"
    uid: d14b4c0f-ca0a-4992-b004-7e5bb97cb4e5
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-10-22T15:16:24Z"
    name: default
    namespace: tekton-dashboard
    resourceVersion: "1581741"
    uid: 533388e4-4d3c-4309-a5c0-e942a4994f2e
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-10-24T16:55:33Z"
    name: default
    namespace: tekton-pipelines-resolvers
    resourceVersion: "1754073"
    uid: 95586948-db10-4e86-83f9-82cd5d80a644
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"resolvers","app.kubernetes.io/instance":"default","app.kubernetes.io/part-of":"tekton-pipelines"},"name":"tekton-pipelines-resolvers","namespace":"tekton-pipelines-resolvers"}}
    creationTimestamp: "2024-10-24T16:55:33Z"
    labels:
      app.kubernetes.io/component: resolvers
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: tekton-pipelines
    name: tekton-pipelines-resolvers
    namespace: tekton-pipelines-resolvers
    resourceVersion: "1754076"
    uid: 17dc6620-3df4-45c1-8be1-ffb65f08ec72
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-10-24T16:55:32Z"
    name: default
    namespace: tekton-pipelines
    resourceVersion: "1753958"
    uid: d5e1e244-eb71-48f1-a198-0b322686b8a4
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"dashboard","app.kubernetes.io/instance":"default","app.kubernetes.io/part-of":"tekton-dashboard"},"name":"tekton-dashboard","namespace":"tekton-pipelines"}}
    creationTimestamp: "2024-10-29T09:17:00Z"
    labels:
      app.kubernetes.io/component: dashboard
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: tekton-dashboard
    name: tekton-dashboard
    namespace: tekton-pipelines
    resourceVersion: "1931172"
    uid: f28e3b56-a1a3-414a-a7dc-ed1b8bdd5a61
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"events","app.kubernetes.io/instance":"default","app.kubernetes.io/part-of":"tekton-pipelines"},"name":"tekton-events-controller","namespace":"tekton-pipelines"}}
    creationTimestamp: "2024-10-24T16:55:32Z"
    labels:
      app.kubernetes.io/component: events
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: tekton-pipelines
    name: tekton-events-controller
    namespace: tekton-pipelines
    resourceVersion: "1753969"
    uid: 4d39f9cb-ee41-43af-befa-d6faa50d8f41
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"controller","app.kubernetes.io/instance":"default","app.kubernetes.io/part-of":"tekton-pipelines"},"name":"tekton-pipelines-controller","namespace":"tekton-pipelines"}}
    creationTimestamp: "2024-10-24T16:55:32Z"
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: tekton-pipelines
    name: tekton-pipelines-controller
    namespace: tekton-pipelines
    resourceVersion: "1753967"
    uid: 4ead4618-1985-4ceb-8724-2e90081a71ca
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"webhook","app.kubernetes.io/instance":"default","app.kubernetes.io/part-of":"tekton-pipelines"},"name":"tekton-pipelines-webhook","namespace":"tekton-pipelines"}}
    creationTimestamp: "2024-10-24T16:55:32Z"
    labels:
      app.kubernetes.io/component: webhook
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: tekton-pipelines
    name: tekton-pipelines-webhook
    namespace: tekton-pipelines
    resourceVersion: "1753968"
    uid: 5dfd4600-eb9e-48e3-8b58-1ff7661a356c
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"default","app.kubernetes.io/part-of":"tekton-triggers"},"name":"tekton-triggers-controller","namespace":"tekton-pipelines"}}
    creationTimestamp: "2024-10-30T10:12:31Z"
    labels:
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: tekton-triggers
    name: tekton-triggers-controller
    namespace: tekton-pipelines
    resourceVersion: "2030026"
    uid: 5d474cc5-6e50-40e4-93ad-65e2e6dfb46e
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"default","app.kubernetes.io/part-of":"tekton-triggers"},"name":"tekton-triggers-core-interceptors","namespace":"tekton-pipelines"}}
    creationTimestamp: "2024-10-30T10:12:31Z"
    labels:
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: tekton-triggers
    name: tekton-triggers-core-interceptors
    namespace: tekton-pipelines
    resourceVersion: "2030028"
    uid: aae3f111-9ebd-44d3-bd83-f852a0fe839b
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"default","app.kubernetes.io/part-of":"tekton-triggers"},"name":"tekton-triggers-webhook","namespace":"tekton-pipelines"}}
    creationTimestamp: "2024-10-30T10:12:31Z"
    labels:
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: tekton-triggers
    name: tekton-triggers-webhook
    namespace: tekton-pipelines
    resourceVersion: "2030027"
    uid: bba30585-2a81-446d-95e6-bd2accb46b16
kind: List
metadata:
  resourceVersion: ""
