apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: spring-app-deployment-apply
spec:
  workspaces:
    - name: output
  steps:
    - name: deploy
      image: bitnami/kubectl:latest
      script: |
        #!/bin/sh
        kubectl apply -f $(workspaces.output.path)/tekton/pipeline/spring-app-deployment.yml
        kubectl apply -f $(workspaces.output.path)/tekton/pipeline/spring-app-service.yml
