apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-petclinic-deployment
  labels:
    app: tekton-petclinic-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-petclinic-pod
  template:
    metadata:
      labels:
        app: tekton-petclinic-pod
      annotations:
        pod-name: tekton-petclinic-deployment
    spec:
      containers:
        - name: springboot-container
          image: juezignasi/tekton-app:latest # Use the image pushed to DockerHub
          ports:
            - containerPort: 8080 # Port on which your app listens
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "mysql" # Set the profile if needed
            - name: MYSQL_URL
              value: "jdbc:mysql://tekton-mysql-service:3306/petclinic"  # Adjust based on your MySQL service
            - name: MYSQL_USER
              value: "petclinic" # MySQL username
            - name: MYSQL_PASS
              value: "petclinic" # MySQL password
      imagePullSecrets:
        - name: dockerhub-secret # Reference the secret to access DockerHub
