apiVersion: v1
kind: Service
metadata:
  name: tekton-petclinic-service
  labels:
    app: tekton-petclinic-service
spec:
  selector:
    app: tekton-petclinic-pod
  ports:
    - protocol: TCP
      port: 80 # Port exposed inside the cluster
      targetPort: 8080 # Port on which your application is running inside the pod
      nodePort: 30007 # Port that will be accessible externally (choose an available port)
  type: NodePort
