apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-template
spec:
  params:
    - name: repo-url
      description: The URL of the Git repository
      default: "https://github.com/ignasijuez/CICD_tekton.git"
    - name: image-reference
      description: The Docker image reference
      default: "juezignasi/tekton-app:latest"
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: ci-pipeline-run-
      spec:
        pipelineRef:
          name: ci-pipeline
            #  podTemplate:
            #securityContext:
            #fsGroup: 65532
        ttlSecondsAfterFinished: 3600  # Tiempo (s) que se conservará el pod tras finalizar
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: docker-credentials
            secret:
              secretName: docker-credentials
        params:
          - name: repo-url
            value: https://github.com/ignasijuez/CICD_tekton.git
          - name: image-reference
            value: juezignasi/tekton-app:latest
          - name: SONAR_PROJECT_KEY
            value: ignasijuez_tekton
          - name: SONAR_ORGANIZATION
            value: ignasijuez